name: Build and Deploy Code

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "feature_pics"
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi bro
        run: echo "hello bro"
